version: '3'
services: 
  
  rabbit:
    image: "rabbitmq:3-management"
    environment: 
      RABBIT_ERLANG_COOKIE: "SWQOKODSQALRPCCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"